[build]
  command = "npm ci && npx prisma generate && npx prisma migrate deploy && npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-optional"
  NEXT_TELEMETRY_DISABLED = "1"
  DATABASE_URL = "postgres://postgres.uwzswsqvmcinkczzlutv:QwiGPYeapGoXuDESYrby22D+7251FxOkEIVW+efAxdHJE8BQwzNRvHHu3qMrN49R93y9b2Nvx503bY6Hw5j+lw==@aws-0-sa-east-1.pooler.supabase.com:5432/postgres"

[[plugins]]
  package = "@netlify/plugin-nextjs"
