[build]
  command = "npm ci && npx prisma generate && npx prisma migrate deploy && npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-optional"
  NEXT_TELEMETRY_DISABLED = "1"
  DIRECT_URL = "postgresql://postgres.uwzswsqvmcinkczzlutv:QwiGPYeapGoXuDESYrby22D%2B7251FxOkEIVW%2BefAxdHJE8BQwzNRvHHu3qMrN49R93y9b2Nvx503bY6Hw5j%2Blw%3D%3D@db.uwzswsqvmcinkczzlutv.supabase.co:5432/postgres"
  DATABASE_URL = ${DIRECT_URL}

[[plugins]]
  package = "@netlify/plugin-nextjs"
