[build]
  command = "npm install && npx prisma generate && npx prisma migrate deploy && npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --production=false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
