services:
  - type: web
    name: musicoterapia-app
    env: node
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        value: postgresql://postgres.uwzswsqvmcinkczzlutv:[YOUR-PASSWORD]@aws-0-sa-east-1.pooler.supabase.com:6543/postgres?pgbouncer=true
      - key: DIRECT_URL
        value: postgresql://postgres.uwzswsqvmcinkczzlutv:[YOUR-PASSWORD]@aws-0-sa-east-1.pooler.supabase.com:5432/postgres
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        value: https://musetera.onrender.com
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://uwzswsqvmcinkczzlutv.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3enN3c3F2bWNpbmtjenpsdXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1MTQ4ODksImV4cCI6MjA1MjA5MDg4OX0.iCtR9Aact4v54BwNSioKTBgey9iAYSafisKkd2RjS5I
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
    autoDeploy: true
    healthCheckPath: /api/health
